### ISSUE TITLE
Can not load Plugin

### ISSUE THREAD

**Issue by Historyman** [revolunet/sublimetext-google-apps-scripts#10]
I installed the plugin via package control.  The Preferences section has a section for Google Apps Script  but I can not find it in the Command Palate 

Here is my console log:
startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Windows/system32
packages path: /C/Users/ajeske/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/ajeske/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\00-package_control.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\01-ssl-windows.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-bz2.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-select-windows.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\GoogleAppsScripts.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\GoogleAppsScripts.py", line 17, in <module>
    import ScriptsBrowser
  File ".\ScriptsBrowser.py", line 19, in <module>
    import GoogleOAuth2
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\GoogleOAuth2.py", line 4, in <module>
    import httplib2
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\httplib2\__init__.py", line 95, in <module>
    from iri2uri import iri2uri
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\httplib2\iri2uri.py", line 100
    self.assertEqual("http://xn--o3h.com/%E2%98%84", iri2uri(u"http://\N{COMET}.com/\N{COMET}"))
SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\ScriptsBrowser.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\ScriptsBrowser.py", line 19, in <module>
    import GoogleOAuth2
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\GoogleOAuth2.py", line 4, in <module>
    import httplib2
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\httplib2\__init__.py", line 95, in <module>
    from iri2uri import iri2uri
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\lib\httplib2\iri2uri.py", line 100
    self.assertEqual("http://xn--o3h.com/%E2%98%84", iri2uri(u"http://\N{COMET}.com/\N{COMET}"))
SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\SublimeHelper.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Package Control\bootstrap.py
plugin init time: 0.172151
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.245084
startup cache, total files: 98 cache hits: 98
startup time: 0.275299 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2015-05-01 11:25:15, next run at 2015-05-01 12:25:15 or after

**Comment by revolunet** [comment]
thanks for reporting.

just removed the faulty code, can you please upgrade the plugin and try again ?

thanks

**Comment by Historyman** [comment]
Ok now the addon seems to working, but I am having an issue with authentication

Traceback (most recent call last):
  File ".\GoogleAppsScripts.py", line 30, in finished
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\sublimetext-google-apps-scripts\lib\GoogleOAuth2.py", line 39, in set_token
    self.storage.put(credentials)
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\sublimetext-google-apps-scripts\lib\oauth2client\client.py", line 325, in put
    self.locked_put(credentials)
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\sublimetext-google-apps-scripts\lib\oauth2client\file.py", line 111, in locked_put
    self._create_file_if_needed()
  File "C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\sublimetext-google-apps-scripts\lib\oauth2client\file.py", line 97, in _create_file_if_needed
    open(self._filename, 'a+b').close()
IOError: [Errno 2] No such file or directory: u'C:\Users\ajeske\AppData\Roaming\Sublime Text 2\Packages\Google Apps Scripts\credentials.json'

Looks like its not finding the file to store my credentials?
