### ISSUE TITLE
some of my GA scripts could open in sublime, some couldn´t

### ISSUE THREAD

**Issue by filipknapcik** [revolunet/sublimetext-google-apps-scripts#12]
Hello,

I have trouble with your package. I would like run it on pc with win8.1+sublime2. Installation was ok, but bigger part of my GASs isn't possible to open - in console I can see "windows errror". On my second PC with win7 it looks ok. 

Any ideas?

thanks in advance,

Filip

**Comment by revolunet** [comment]
nop sorry, didnt try with windows... try to have a traceback in the sublime console.
so it works  OK with win 7 ?

**Comment by filipknapcik** [comment]
hi,
please check console log below. With win7 it looks ok.

startup, version: 2221 windows x64 channel: stable
executable: /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/sublime_text.exe
working dir: /c/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64
packages path: /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages
settings path: /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64
Py_GetProgramFullPath(): C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\sublime_text.exe
Py_GetPath(): C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\python26.zip;C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\DLLs;C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\lib;C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\lib\plat-win;C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\lib\lib-tk;C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64
Py_GetPythonHome(): C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64
catalogue loaded
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\0_package_control_loader\00-package_control.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\0_package_control_loader\01-ssl-windows.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\0_package_control_loader\02-bz2.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\0_package_control_loader\02-select-windows.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\CSS\css_completions.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\comment.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\copy_path.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\delete_word.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\echo.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\exec.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\fold.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\font.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\goto_line.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\indentation.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\kill_ring.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\mark.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\new_templates.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\paragraph.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\scroll.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\side_bar.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\sort.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\swap_line.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\switch_file.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\transform.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\transpose.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Diff\diff.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\HTML\html_completions.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Package Control\bootstrap.py
plugin init time: 0.226878
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.4071
startup cache, total files: 96 cache hits: 96
startup time: 0.443042 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2015-09-06 13:50:04, next run at 2015-09-06 14:50:04 or after
ignored packages updated to: [Vintage, Google Apps Scripts]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Package Control.sublime-settings
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Package Control.sublime-settings
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Package Control.sublime-settings
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Google Apps Scripts\GoogleAppsScripts.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Google Apps Scripts\ScriptsBrowser.py
Reloading plugin C:\Users\Filip\Downloads\softs\Sublime Text 2.0.2 x64\Data\Packages\Google Apps Scripts\SublimeHelper.py
found 3 files for base name Main.sublime-menu
theme loaded
reloading /C/Users/Filip/Downloads/softs/Sublime Text 2.0.2 x64/Data/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
No handlers could be found for logger "oauth2client.util"
project_selected 5
Traceback (most recent call last):
  File ".\GoogleAppsScripts.py", line 125, in callback
  File ".\GoogleAppsScripts.py", line 141, in file_selected
  File ".\SublimeHelper.py", line 25, in write
WindowsError:

**Comment by filipknapcik** [comment]
hey, no solution? :/
